# Pandas

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Series

-   contains
    -   a one-dimensional array of data
    -   the index an associated sequence of labels called
        -   The index can contain numeric, string, or date/time values.
        -   When the index is a time value, the series is a time series.
        -   The index must be the same length as the data.
    -   If no index is supplied it is automatically generated as range(len(data)).

In [ ]:
print(pd.Series([1, 2, 3, 4]))
d = {'a': 0., 'b': 1., 'c': 2.}
print(pd.Series(d))
data = [0.03245675,  0.41263151, -0.27993028, -0.95398035, -0.01473876]
my_series = pd.Series(data, index=['a', 'b', 'c', 'd', 'e'])
print(my_series)

In [ ]:
my_series.plot()
plt.show()

In [ ]:
pd.Series(d) ** 2

In [ ]:
x = pd.Series({'a': 0., 'b': 1., 'c': 2.})
y = pd.Series({'a': 3., 'b': 4., 'c': 5.})
x + y

In [ ]:
dates = pd.date_range('1/1/2000', periods=5)
print(dates)
time_series = pd.Series(data, index=dates)
time_series

In [ ]:
ax = time_series.plot()

In [ ]:
weekly_rets = np.diff(np.log(weekly_prices))
plt.plot(weekly_rets)
plt.xlabel('t')
plt.ylabel('$r_t$')
plt.title('Weekly log-returns for GOOGL')
plt.show()

In [ ]:
from pylab import plt, mpl
import numpy as np

np.random.seed(100)
a = np.random.standard_normal((9, 4))
df = pd.DataFrame(a)
df.columns = ['No1', 'No2', 'No3', 'No4']
df.index = pd.date_range('2019-1-1', periods=9, freq='M')


plt.style.use('seaborn')
mpl.rcParams['font.family'] = 'serif'

%matplotlib inline
df.cumsum().plot(lw=2.0, figsize=(10, 6))

df.plot.bar(figsize=(10, 6), rot=15)

In [ ]:
S = pd.Series(np.linspace(0, 15, 7), name='series')

df['No1'].plot(lw=2.0, figsize=(10, 6))

In [ ]:
df['Quarter'] = ['Q1', 'Q1', 'Q1', 'Q2', 'Q2',
                 'Q2', 'Q3', 'Q3', 'Q3']
groups = df.groupby('Quarter')
groups.aggregate([min, max]).round(2)

In [ ]:
df['Odd_Even'] = ['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
                  'Odd', 'Even', 'Odd']
groups = df.groupby(['Quarter', 'Odd_Even'])
groups[['No1', 'No4']].aggregate([sum, np.mean])

In [ ]:
ata = np.random.standard_normal((10, 2))
df = pd.DataFrame(data, columns=['x', 'y'])
(df['x'] > 0) & (df['y'] < 0)

## DataFrame

-   A data frame has multiple columns, each of which can hold a different type of value.
-   Like a series, it has an index which provides a label for each and every row.
-   Data frames can be constructed from:
    -   dict of arrays
    -   dict of lists
    -   dict of dict
    -   dict of Series
    -   2-dimensional array
    -   a single Series
    -   another DataFrame

In [ ]:
import pandas as pd
from pandas import Series, DataFrame
data = {'Chinese': [66, 95, 93, 90, 80], 'English': [
    65, 85, 92, 88, 90], 'Math': [30, 98, 96, 77, 90]}
df1 = DataFrame(data)
df2 = DataFrame(data, index=['ZhangFei', 'GuanYu', 'ZhaoYun',
                'HuangZhong', 'DianWei'], columns=['English', 'Math', 'Chinese'])
print(df1)
print(df2)

In [ ]:
series_dict = {
    'x': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
    'y': pd.Series([4., 5., 6., 7.], index=['a', 'b', 'c', 'd']),
    'z': pd.Series([0.1, 0.2, 0.3, 0.4], index=['a', 'b', 'c', 'd'])
}
print(series_dict)
df = pd.DataFrame(series_dict)
print(df)
print(df.index)
print(df.columns)
df.plot()

In [ ]:
print(df.x.b)
print(df['x']['a'])
print(df['y'][['b', 'd']])
df[['x', 'z']]

In [ ]:
df.x + df.y

In [ ]:
df['x'] >= 2

In [ ]:
df[df['x'] >= 2]

In [ ]:
df.describe()

In [ ]:
df.describe()['x']['mean']

In [ ]:
googl = pd.read_csv('../data/GOOGLE.csv')
googl.head()
googl.tail()
pd.to_datetime(googl['Date'])

In [ ]:
# 导入导出
import pandas as pd
from pandas import Series, DataFrame
score = DataFrame(pd.read_excel('data.xlsx'))
score.to_excel('data1.xlsx')
print(score)

In [ ]:
googl.set_index(pd.to_datetime(googl['Date']), inplace=True)
googl.index[0]

In [ ]:
ax1 = googl['Volume'].plot()
plt.show()

In [ ]:
googl['Adj Close']['6-6-2019':'11-11-2019'].plot()
plt.show()

In [ ]:
weekly_prices.plot()
plt.title('Prices for GOOGL sampled at weekly frequency')
plt.show()

In [ ]:
df = pd.DataFrame({
    'Letter': ['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c'],
    'X': [4, 3, 5, 2, 1, 7, 7, 5, 9],
    'Y': [0, 4, 3, 6, 7, 10, 11, 9, 13],
    'Z': [1, 2, 3, 1, 2, 3, 1, 2, 3]
})

% % R - i df ggplot(data=df) + geom_point(aes(x=X, y=Y, color=Letter, size=Z))

In [ ]:
df1 = pd.DataFrame([10, 20, 30, 40],  columns=[
                   'numbers'], index=['a', 'b', 'c', 'd'])
df1

### 数据清洗

In [ ]:
data = {
    'Chinese': [66, 95, 93, 90, 80],
    'English': [65, 85, 92, 88, 90],
    'Math': [30, 98, 96, 77, 90],
    'Str': ['aaaa', 'bbbb', 'ccccc', 'ddddd', 'eeeee']
}
df2 = DataFrame(data, index=['ZhangFei', 'GuanYu', 'ZhaoYun', 'HuangZhong', 'DianWei'],
                columns=['English', 'Math', 'Chinese', 'Str'])

In [ ]:
df2.rename(columns={'Chinese': 'YuWen', 'English': 'Yingyu'}, inplace=True)
print(df2)

In [ ]:
print(df2)
df2 = df2.drop(columns=['YuWen'])
print(df2)

df2 = df2.drop(index=['ZhangFei'])
print(df2)

In [ ]:
df2['Str'] = df2['Str'].apply(str.upper)
print(df2)

In [ ]:
def double_df(x):
    return 2*x


# df1[u'语文'] = df1[u'语文'].apply(double_df)
df2['Yingyu'] = df2['Yingyu'].apply(double_df)
print(df2)

### 格式问题

In [ ]:
df2['YuWen'].astype('str')
print(df2)

In [ ]:
df2['YuWen']['GuanYu'] = "$99"
print(df2)
df2['YuWen'] = df2['YuWen'].str.strip('$')
print(df2)

In [ ]:
print(df2.isnull())

In [ ]:
# 全部大写
df2.columns = df2.columns.str.upper()
print(df2)
# 全部小写
df2.columns = df2.columns.str.lower()
print(df2)
# 首字母大写
df2.columns = df2.columns.str.title()
print(df2)

### 数据统计

In [ ]:
df2.describe()

In [ ]:
print(df2)
df2.median()

In [ ]:
print(df2['Yingyu'].argmin())

### 数据表合并

In [ ]:
df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
df2 = DataFrame({'name':['ZhangFei', 'GuanYu', 'A', 'B', 'C'], 'data2':range(5)})

In [ ]:
pd.merge(df1, df2, on='name')

In [ ]:
df3 = pd.merge(df1, df2, how='inner')
df3

In [ ]:
pd.merge(df1, df2, how='left')

In [ ]:
pd.merge(df1, df2, how='outer')

In [ ]:

import pandas as pd
from pandas import DataFrame
from pandasql import sqldf, load_meat, load_births

df1 = DataFrame({'name':['ZhangFei', 'GuanYu', 'a', 'b', 'c'], 'data1':range(5)})
pysqldf = lambda sql: sqldf(sql, globals())
sql = "select * from df1 where name ='ZhangFei'"
print(pysqldf(sql))

## 练习

In [159]:
data = {
    "语文": [66, 95, 95, 90, 80, 80],
    "英语": [65, 85, 92, 88, 90, 90],
    "数学": [None, 98, 96, 77, 90,90]}
df = DataFrame(data,
                index=["张飞", "关羽", "赵云", "黄忠", "典韦", "典韦"],
                columns=["语文", "英语", "数学"])
df

    语文  英语    数学
张飞  66  65   NaN
关羽  95  85  98.0
赵云  95  92  96.0
黄忠  90  88  77.0
典韦  80  90  90.0
典韦  80  90  90.0

In [160]:
df = df.drop_duplicates()
df

    语文  英语    数学
张飞  66  65   NaN
关羽  95  85  98.0
赵云  95  92  96.0
黄忠  90  88  77.0
典韦  80  90  90.0

In [161]:
cols = ['英语', '语文', '数学']

df = df.filter(cols, axis=1)
df

    英语  语文    数学
张飞  65  66   NaN
关羽  85  95  98.0
赵云  92  95  96.0
黄忠  88  90  77.0
典韦  90  80  90.0

In [ ]:
def total_score(df):
    df['总分'] = df['语文'] + df['英语'] + df['数学']
    return df


# 用 apply 方法求成绩的和
df1 = df.apply(total_score, axis=1)
df1

In [163]:
df["总分数"] = df.sum(axis=1)
df

    英语  语文    数学    总分数
张飞  65  66   NaN  262.0
关羽  85  95  98.0  556.0
赵云  92  95  96.0  566.0
黄忠  88  90  77.0  510.0
典韦  90  80  90.0  520.0

In [164]:
# df['总分'] = df['语文'] + df['英语'] + df['数学']
# 按照总分排序，从高到低，此时有缺失值
df.sort_values(['总分'], ascending=[False], inplace=True)

# 打印显示成绩单信息，张飞有空值
print(df.isnull().sum())
print(df)

KeyError: '总分'

In [ ]:
# 使用数学成绩均值填充张飞同学的缺失值
df['数学'].fillna(df['数学'].mean(), inplace=True)

# 再次求成绩的和并打印显示成绩单情况
df = df.apply(total_score, axis=1)
print(df.isnull().sum())
print(df)